=== AlbertoCS8/EntDes/XSLT/Empleadodedtd.dtd
<!ELEMENT empleados (empleado)>
<!ELEMENT empleado (nombre,apellidos,movil,direcciones)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT direcciones (direccion+)>
<!ELEMENT direccion (#PCDATA)>

=== AlbertoCS8/EntDes/XSLT/Empleadodedtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE empleados SYSTEM "Empleadodedtd.dtd">
<empleados>
    <empleado>
        <nombre>
            pepito
        </nombre>
        <apellidos>
            sanchez
        </apellidos>
        <movil>
            666666666
        </movil>
        <!--<fijo></fijo>-->
        <direcciones>
            <direccion>
                Dir 1
            </direccion>
            <direccion>
                Dir 2
            </direccion>
        </direcciones>
    </empleado>
</empleados>
